application:
  repository:
    query-limit-warning-ms: 300

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  config:
    activate:
      on-profile: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/Haus
  
  #DATABASE
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/haus?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:Quankane1905@}
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
      use_sql_comments: true
  #  kafka:
  #    bootstrap   -servers: localhost:29092
  #  redis:
  #    host: ${REDIS_HOST:localhost}
  #    port: ${REDIS_PORT:6379}
  sendGrid:
    apiKey: ${SENDGRID_API_KEY}
    fromEmail: quanducbui2017@gmail.com
    templateRegistrationId: d-2c32e3d6a2644029abe158ce9457aab4
    templateForgotId: d-a71ca0b41fc1437ca11a3002a0235c19
    imagePrev: https://res.cloudinary.com/dgwnoquie/image/upload/v1755789933/image-43_f3kmgh.jpg
    imageNext: https://res.cloudinary.com/dgwnoquie/image/upload/v1755790009/KHACH-BEP-15_bj8u43.jpg
    logo: https://res.cloudinary.com/dgwnoquie/image/upload/v1755791051/HAUS-logo_byhum7.jpg

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: Haus
    server: http://localhost:${server.port}
    title: ${API_TITLE:DUMMY API TITLE}
    version: v1.0.0

#Security Endpoint
security:
  public-endpoints: /oauth2/**, /auth/**, /api/v1/auth/**, /api/v1/payment/**
  user-endpoints: /api/v1/user/**
  admin-endpoints: /api/v1/admin/**, /api/v1/promotion/**, /api/v1/category/**, /api/v1/product/**
  swagger-endpoints: /swagger-ui/**, /v3/api-docs/**, /swagger-ui.html

#JWT
jwt:
  expiryHour: 1
  expiryDay: 1
  accessKey: c2VjcmV0QGtleS5hcGlfaGFzX2JlZW5fZGVzaWduZWRfYnlfVGF5TFE=
  refreshKey: 9k1jJAWAKQCnCEz1pwcPNegbHoLugf9hgEnn6sz5pFc=

#Cloudinary
cloudinary:
  cloud_name: ${CLOUDINARY_NAME:dgwnoquie}
  api_key: ${CLOUDINARY_API_KEY:671838345639772}
  secret_key: ${CLOUDINARY_SECRET_KEY:-xdwjAMbATWoIvkpbT_-6K5TuIg}

#VnPay
payment:
  vnPay:
    url: ${VNPAY_URL}
    returnUrl: ${VNPAY_RETURN_URL}
    tmnCode: ${VNPAY_TMN_CODE}
    hashSecret: ${VNPAY_HASH_SECRET}
    apiUrl: ${VNPAY_API_URL}
    version: ${VNPAY_VERSION}
    command: ${VNPAY_COMMAND:pay}
    maxTime: ${VNPAY_MAXTIME}
    orderType: ${VNPAY_ORDER_TYPE:other}
    currCode: ${VNPAY_CURRCODE:VND}
    locale: ${VNPAY_LOCALE:vn}

#KeyCloak
keycloak:
  serverUrl: ${KEYCLOAK_SERVERURL}
  realm: ${KEYCLOAK_REALM}
  clientId: ${KEYCLOAK_CLIENTID}
  clientSecret: ${KEYCLOAK_CLIENTSECRET}
  adminUser: ${KEYCLOAK_ADMINUSER}
  adminPassword: ${KEYCLOAK_ADMINPASSWORD}